#qlogin -P "sament-lab" -l mem_free=100G -q interactive.q -pe thread 16

.libPaths('/local/projects-t3/idea/bherb/software/R_lib/R_3_6')
library(Seurat,lib.loc='/usr/local/packages/r-3.6.0/lib64/R/library') ## 3.0.1
#library(Seurat)
library(BiocGenerics)
library(monocle3)
library(projectR)
library(plotrix) # updated
library(xlsx)
library(ggplot2)
library(impute)
library(preprocessCore) 
library(AnnotationDbi)
library(GO.db)
library(dendextend)
library(matrixStats)
library(Matrix)
library(scrattch.hicat)
library(scDblFinder)
#library(future)
library(RColorBrewer)
library(GENIE3)
library(feather)
library(slingshot)
library(gam)
library(tradeSeq)
library(RColorBrewer)
library(SingleCellExperiment)
library(WGCNA)
library(AUCell)
library(MetaNeighbor)
#library(topGO)
library('GOstats')
library('GO.db')
library('org.Hs.eg.db')
library("biomaRt")
#library(scran,lib.loc='/usr/local/packages/r-3.6.0/lib64/R/library')
library(EnhancedVolcano)
library( cicero )